### PR TITLE
Assembly signing

### PR DESCRIPTION
**Pull request by Ximik87**
I contributing for CoreWCF repository, and want add support MSMQ transport (detail [here](https://github.com/CoreWCF/CoreWCF/issues/164)). I need that Nuget package have strong name. I prepared this PR, to needed changes. Is it possible ?

### CODE REVIEW

**Review by weloytty — APPROVED** [review]

**Comment by weloytty** [comment]
since all of this code only works on Windows (mqrt.dll), I didn't think it would be useful for something like that, but I am glad to be wrong about it.  Thanks for your help!

**Comment by Ximik87** [comment]
Could you bump the version so that the changes go into the new Nuget version? Thank you!

**Comment by bstordrup** [comment]
I would like a new Nuget version with this signing.

**Comment by bstordrup** [comment]
@weloytty, would it be possible to get a nuget version 1.0.3 with the assembly signing?

**Comment by weloytty** [comment]
Sorry that took so long, I had to find my nuget account and password.  https://www.nuget.org/packages/MSMQ.Messaging

**Pull request merged**
